//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.74:8013/JaizService/Service.asmx")]
        public string HRViabilityPortal_ADDetais_Service {
            get {
                return ((string)(this["HRViabilityPortal_ADDetais_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.160:8013/JaizInternetBankingApi/JaizHelper.svc")]
        public string HRViabilityPortal_InternetBankingHelper_JaizHelper {
            get {
                return ((string)(this["HRViabilityPortal_InternetBankingHelper_JaizHelper"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.160:8013/RoleManagerService/JaizRoleManagerService.svc")]
        public string HRViabilityPortal_JaizRoleManager_JaizRoleManagerService {
            get {
                return ((string)(this["HRViabilityPortal_JaizRoleManager_JaizRoleManagerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jz-srv-aps9-2:8080/HRViabilityDocumentsService/DocumentGenerator")]
        public string HRViabilityPortal_DocumentGenerator_DocumentGenerator {
            get {
                return ((string)(this["HRViabilityPortal_DocumentGenerator_DocumentGenerator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/HRViabilityDocumentsService/DocumentGenerator")]
        public string HRViabilityPortal_TestDocGenerator_DocumentGenerator {
            get {
                return ((string)(this["HRViabilityPortal_TestDocGenerator_DocumentGenerator"]));
            }
        }
    }
}
