//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ActivityPerformed { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateOfActivity { get; set; }
        public string IpAddress { get; set; }
    }
}
