//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailBox
    {
        public long ID { get; set; }
        public string EmailAddress { get; set; }
        public string EmailContent { get; set; }
        public Nullable<int> HasAttachment { get; set; }
        public string Attachment { get; set; }
        public string EmailStatus { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string Platform { get; set; }
        public string FromAddress { get; set; }
        public string Subject { get; set; }
    }
}
