//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAccount
    {
        public int emailID { get; set; }
        public string emailName { get; set; }
        public string emailAddress { get; set; }
        public string emailPassword { get; set; }
        public string emailGateway { get; set; }
        public string emailUserName { get; set; }
        public int emailStatus { get; set; }
        public Nullable<int> emailINTBK { get; set; }
    }
}
