//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int id { get; set; }
        public string facilityName { get; set; }
        public string confirmedStaff { get; set; }
        public string unconfirmedStaff { get; set; }
        public string permanentStaff { get; set; }
        public string contractStaff { get; set; }
        public Nullable<int> expectedLengthOfService { get; set; }
        public Nullable<decimal> percentageRate { get; set; }
        public Nullable<decimal> staffBranchPercentageRate { get; set; }
        public Nullable<decimal> minimumAnnualGrossAllowance { get; set; }
        public Nullable<decimal> minimumAnnualHousingAllowance { get; set; }
        public Nullable<decimal> maximumAmountLimit { get; set; }
        public string totalDeductionFromSalary { get; set; }
        public Nullable<int> minimumTenor { get; set; }
        public Nullable<int> maximumTenor { get; set; }
        public string undertakingFormNeeded { get; set; }
        public string supervisorEndorsementNeeded { get; set; }
        public string searchAuthorityNeeded { get; set; }
        public string active { get; set; }
        public string facilityComments { get; set; }
        public string document1 { get; set; }
        public string document2 { get; set; }
        public string document3 { get; set; }
        public string document4 { get; set; }
        public string document5 { get; set; }
        public string document6 { get; set; }
        public string document7 { get; set; }
        public string document8 { get; set; }
        public string document9 { get; set; }
        public string document10 { get; set; }
        public string form1 { get; set; }
        public string form2 { get; set; }
        public string form3 { get; set; }
        public string form4 { get; set; }
        public string form5 { get; set; }
        public string form6 { get; set; }
        public string form7 { get; set; }
        public string form8 { get; set; }
        public string form9 { get; set; }
        public string form10 { get; set; }
        public string facilityRulesComments { get; set; }
        public string facilityRulesSet { get; set; }
        public string maximumAmountLimitOption { get; set; }
        public string mdApproval { get; set; }
        public string downPaymentRequired { get; set; }
        public string dhApproval { get; set; }
        public string customField1 { get; set; }
        public string customField2 { get; set; }
        public string customField3 { get; set; }
        public string customField4 { get; set; }
        public string customField5 { get; set; }
        public string customField6 { get; set; }
        public string customField7 { get; set; }
        public string customField8 { get; set; }
        public string customField9 { get; set; }
        public string customField10 { get; set; }
    }
}
