//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRFacilityMaster
    {
        public long ID { get; set; }
        public string requestReferenceNumber { get; set; }
        public string staffId { get; set; }
        public string accountNumber { get; set; }
        public Nullable<int> cif { get; set; }
        public string accountName { get; set; }
        public string facilityName { get; set; }
        public string salaryGrade { get; set; }
        public string mobileNumber { get; set; }
        public string maritalStatus { get; set; }
        public string dateOfBirth { get; set; }
        public string staffEmailAddress { get; set; }
        public string state { get; set; }
        public string natureOfEmployment { get; set; }
        public Nullable<int> numberOfMonthsInService { get; set; }
        public string jobFunction { get; set; }
        public string branch { get; set; }
        public string branchCode { get; set; }
        public string department { get; set; }
        public decimal grossAnnualSalary { get; set; }
        public decimal netMonthlySalary { get; set; }
        public Nullable<decimal> annualHousingAllowance { get; set; }
        public Nullable<decimal> outstandingLoanAmount { get; set; }
        public Nullable<int> noOfMonthsRemainingOnfacility { get; set; }
        public decimal amountRequested { get; set; }
        public Nullable<decimal> downPaymentContribution { get; set; }
        public Nullable<decimal> repaymentAmount { get; set; }
        public Nullable<decimal> percentageRate { get; set; }
        public int tenor { get; set; }
        public string loanPurpose { get; set; }
        public string assetDescription { get; set; }
        public string vendorsName { get; set; }
        public string vendorsAddress { get; set; }
        public string vendorsPhoneNumber { get; set; }
        public string locationOfAsset { get; set; }
        public string vehicleModel { get; set; }
        public string yearOfManufacture { get; set; }
        public string modeOfDelivery { get; set; }
        public string quotationEnclosed { get; set; }
        public string typeOfProperty { get; set; }
        public string propertyDescription { get; set; }
        public string titleDocumentType { get; set; }
        public string nameOfDeveloper { get; set; }
        public string addressOfDeveloper { get; set; }
        public string phoneNumberOfDeveloper { get; set; }
        public string locationOfProperty { get; set; }
        public string serviceDescription { get; set; }
        public string serviceProviderName { get; set; }
        public string serviceProviderAddress { get; set; }
        public string servicePhoneNumber { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public string requestStatus { get; set; }
        public string initiator { get; set; }
        public Nullable<System.DateTime> initiatorTimestamp { get; set; }
        public string staffSupervisor { get; set; }
        public string hrApprover1 { get; set; }
        public string hrApprover1ApproveReject { get; set; }
        public string hrApprover1Comment { get; set; }
        public Nullable<System.DateTime> hrApprover1Timestamp { get; set; }
        public string hrApprover2 { get; set; }
        public Nullable<System.DateTime> hrApprover2Timestamp { get; set; }
        public string hrApprover2ApproveReject { get; set; }
        public string hrApprover2Comment { get; set; }
        public string bmBranchOfRequest { get; set; }
        public Nullable<System.DateTime> bmBranchOfRequestTimestamp { get; set; }
        public string bmBranchOfRequestApproveReject { get; set; }
        public string bmBranchOfRequestComment { get; set; }
        public string mdApprover { get; set; }
        public Nullable<System.DateTime> mdApproverTimestamp { get; set; }
        public string mdApproverApproveReject { get; set; }
        public string mdApproverComment { get; set; }
        public string fileName1 { get; set; }
        public string fileContentType1 { get; set; }
        public string fileData1 { get; set; }
        public string fileName2 { get; set; }
        public string fileContentType2 { get; set; }
        public string fileData2 { get; set; }
        public string fileName3 { get; set; }
        public string fileContentType3 { get; set; }
        public string fileData3 { get; set; }
        public string fileName4 { get; set; }
        public string fileContentType4 { get; set; }
        public string fileData4 { get; set; }
        public string fileName5 { get; set; }
        public string fileContentType5 { get; set; }
        public string fileData5 { get; set; }
        public string fileName6 { get; set; }
        public string fileContentType6 { get; set; }
        public string fileData6 { get; set; }
        public string hrApprover1RejectComment { get; set; }
        public string hrApprover2RejectComment { get; set; }
        public string mdApproverRejectComment { get; set; }
        public string bmApproverRejectComment { get; set; }
        public string dhApproverRejectComment { get; set; }
        public string dhApprover { get; set; }
        public Nullable<System.DateTime> dhApproverTimestamp { get; set; }
        public string dhApproverApproveReject { get; set; }
        public string dhApproverComment { get; set; }
        public string hasExistingVehicleLoan { get; set; }
        public string hasExistingMortgageLoan { get; set; }
        public string dateOfEmployment { get; set; }
        public string customField1 { get; set; }
        public string customField1Data { get; set; }
        public string customField2 { get; set; }
        public string customField2Data { get; set; }
        public string customField3 { get; set; }
        public string customField3Data { get; set; }
        public string customField4 { get; set; }
        public string customField4Data { get; set; }
        public string customField5 { get; set; }
        public string customField5Data { get; set; }
        public string customField6 { get; set; }
        public string customField6Data { get; set; }
        public string customField7 { get; set; }
        public string customField7Data { get; set; }
        public string customField8 { get; set; }
        public string customField8Data { get; set; }
        public string customField9 { get; set; }
        public string customField9Data { get; set; }
        public string customField10 { get; set; }
        public string customField10Data { get; set; }
        public Nullable<int> queueId { get; set; }
        public string fileName7 { get; set; }
        public string fileContentType7 { get; set; }
        public string fileData7 { get; set; }
        public string fileName8 { get; set; }
        public string fileContentType8 { get; set; }
        public string fileData8 { get; set; }
        public string fileName9 { get; set; }
        public string fileContentType9 { get; set; }
        public string fileData9 { get; set; }
        public string fileName10 { get; set; }
        public string fileContentType10 { get; set; }
        public string fileData10 { get; set; }
        public string documentEmailStatus { get; set; }
        public string documentEmailSentTime { get; set; }
    }
}
