//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPayroll
    {
        public int Id { get; set; }
        public string GradeName { get; set; }
        public string AnnualGrossPackage { get; set; }
        public string AnnualHousingAllowance { get; set; }
        public string MonthlyGrossPackage { get; set; }
        public string MonthlyNetPackage { get; set; }
        public string PensionsContribution { get; set; }
        public string PAYE { get; set; }
        public string NHF { get; set; }
        public string TotalAnnualDeduction { get; set; }
        public string TotalMonthlyDeduction { get; set; }
    }
}
