//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqHistory
    {
        public int sn { get; set; }
        public string ReqId { get; set; }
        public string Initiator { get; set; }
        public string ActionPerformed { get; set; }
        public Nullable<System.DateTime> ActionDateTime { get; set; }
    }
}
