//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRViabilityPortal.Database_References
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffGradesSalary
    {
        public int id { get; set; }
        public string gradeName { get; set; }
        public decimal netMonthlySalary { get; set; }
        public decimal grossAnnualSalary { get; set; }
        public Nullable<decimal> annualHousingAllowance { get; set; }
        public Nullable<bool> isSelected { get; set; }
        public string active { get; set; }
        public string comments { get; set; }
    }
}
